"""create assessments table

Revision ID: 5ef3d75a843a
Revises: 4e6429659cf1
Create Date: 2026-08-28 17:11:17.363402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef3d75a843a'
down_revision: Union[str, Sequence[str], None] = '4e6429659cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.Enum('INTERNAL', 'ASSIGNMENT', 'MIDTERM', 'FINAL', name='assessmenttype'), nullable=False),
    sa.Column('assessment_name', sa.String(length=150), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('obtained_marks', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'assessment_type', 'assessment_name', name='uq_enrollment_assessment')
    )
    op.create_index(op.f('ix_assessments_assessment_date'), 'assessments', ['assessment_date'], unique=False)
    op.create_index(op.f('ix_assessments_assessment_type'), 'assessments', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessments_enrollment_id'), 'assessments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_enrollment_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_type'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_date'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
